# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 75796d4b4a37faf61a336d03fd7772011d98a49402956a9faeba1d5e29f3120f8580398a2c05139f763e9265945598bc9badaf3dbd6ca72e63f57dc61e6b4f3c

test:
  secret_key_base: 17e05dda70f58f804b1368645e1ac8d55143b7cb7776cc48ba2af593fcde55e835d293f2ee0899770ff287488a188e41b50a1487e232205f185d983b456c059c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
